package com.xc.air3xctaddon

enum class Event {
    BATTERY50,
    BATTERY40,
    BATTERY30,
    BATTERY20,
    BATTERY10,
    BATTERY5,
    TAKEOFF,
    LANDING,
    COMP_SSS_CROSSED,
    COMP_TURNPOINT_CROSSED,
    COMP_ESS_CROSSED,
    COMP_GOAL_CROSSED,
    AIRSPACE_CROSSED,
    AIRSPACE_RED_WARN,
    AIRSPACE_ORANGE_WARN,
    AIRSPACE_CROSSED_SOON,
    AIRSPACE_OBSTACLE,
    LIVETRACK_MESSAGE
}